### ISSUE TITLE
Derive configuration rules from swagger files

### ISSUE THREAD

**Issue by dmitrykrivaltsevich** [zalando-incubator/play-zhewbacca#32]
Leo Gallucci highlighted similarity in configuration files with `securityDefinitions` section of swager files:

```
securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    tokenUrl: https://auth.example.com/oauth2/access_token?realm=services
    scopes:
      my-awesome-service.my-resource.operation: Rights to perform operation on my-resource
```

Would be interesting to derive configuration files from swagger files and allow users to override or extend derived rules.
